### ISSUE TITLE
different data input for scode embedding

### ISSUE THREAD

**Issue by adalisan** [ai-ku/scode#2]
instead of sentence of tokens, my data is a co-occurrence probability matrix. Is there a way to get an embedding? Is this trivial to implement in the code?

**Comment by esert** [comment]
You have to provide pairs of tokens to S-CODE and S-CODE will give you an embedding for each token when it's done. As pairs of tokens, you can use sampled pairs from the co-occurrence matrix. Here's some pseudo code for how to do that:

```
// Let P_xy be the n by m co-occurrence matrix, so that P_xy[x][y] is P(x,y) 
// Let P_x be the vector of size n, all elements initialized to zero

for x to n:
  for y to m:
    P_x[x] += P_xy[x][y]
// At this point P_x[x] is P(x)

for i to 1000000 // or some other large number
  // sample function returns a random index from the vector
  // according to probability distribution of the indices
  x = sample(P_x)
  y = sample(P_xy[x])
  print x, y    
```

**Comment by adalisan** [comment]
Ok, I must have misunderstood the nature of your work. I just have to
provide the (x_i,y_i) pairs (as tokens)  where x_i,y_i are drawn from a
discrete distribution? If so, that is good, because I have the data in that
form.

**Comment by esert** [comment]
Yes, you have to input co-occurring pairs to the algorithm. If you have the data (pairs), just use that. If you have a co-occurrence matrix, sample from the matrix as I outlined in the message above.

**Comment by adalisan** [comment]
There are two  embedding  coordinates for each token, one for each location index. Is there a way to get a single embedding for a token? I tried replicating each cooccurrence (a,b) in the dataset  with (b,a), but I still get two different embeddings that are significantly different.

**Comment by esert** [comment]
There is a simple way to deal with this. Let's say a_x is the embedding you get for a's on the left column of the input, and a_y is the embedding you get for a's in the right column. Then you have 3 possible embeddings for your dataset:

1- Using only _x embeddings (a_x)
2- Using only _y embeddings (a_y)
3- Using concatenation of _x and _y embeddings (a_x + a_y, note that + is not addition but concatenation operator). 

Naturally, if some of your tokens are missing in one of the columns, you won't be able to use some of the options above.

See http://www.denizyuret.com/2013/09/enis-rfat-sert-ms-2013.html for application of SCODE to an NLP problem.
